version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    branches:
      only:
        - Lakka-V2.1-dev
    steps:
      - checkout
      - run:
          name: Install Host Dependencies
          command: apt-get update && apt-get install -y xz-utils make wget bash bc gcc sed patch patchutils tar bzip2 gzip perl gawk gperf zip unzip diffutils texinfo lzop libc6-dev libncurses5-dev g++ xfonts-utils xfonts-utils xfonts-utils xsltproc libjson-perl
      - run: echo 'export DISTRO=Lakka' >> $BASH_ENV
      - run: echo 'export PROJECT=Generic' >> $BASH_ENV
      - run: echo 'export ARCH=x86_64' >> $BASH_ENV
      - restore_cache:
          keys:
            - toolchaincache
      - run: scripts/build make:host -j1
      - run: scripts/build ccache:host -j1
      - run: scripts/build xz:host -j1
      - run: scripts/build sed:host -j1
      - run: scripts/build gettext:host -j1
      - run: scripts/build pkg-config:host -j1
      - save_cache:
          key: toolchaincache
          paths:
            - build.Lakka-Generic.x86_64-2.1-devel/make-4.2.1
            - build.Lakka-Generic.x86_64-2.1-devel/ccache-3.3.3
            - build.Lakka-Generic.x86_64-2.1-devel/xz-5.2.3
            - build.Lakka-Generic.x86_64-2.1-devel/sed-4.2.2
            - build.Lakka-Generic.x86_64-2.1-devel/gettext-0.19.8.1
            - build.Lakka-Generic.x86_64-2.1-devel/pkg-config-0.29.1
      - restore_cache:
          keys:
            - buildcache
      - run: make image -j1
      - save_cache:
          key: buildcache
          paths:
            - build.Lakka-Generic.x86_64-2.1-devel

