version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    branches:
      only:
        - Lakka-V2.1-dev
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: Install Host Dependencies
          command: apt-get update && apt-get install -y xz-utils make wget bash bc gcc sed patch patchutils tar bzip2 gzip perl gawk gperf zip unzip diffutils texinfo lzop libc6-dev libncurses5-dev g++ xfonts-utils xfonts-utils xfonts-utils xsltproc libjson-perl
      - run: echo 'export DISTRO=Lakka' >> $BASH_ENV
      - run: echo 'export PROJECT=Generic' >> $BASH_ENV
      - run: echo 'export ARCH=x86_64' >> $BASH_ENV
      - restore_cache:
          keys:
            - build-v1
      - run:
          name: Create swap file
          command: dd if=/dev/zero of=swapfile bs=1M count=2048 && mkswap swapfile && swapon swapfile
      - run: scripts/build make:host
      - run: scripts/build ccache:host
      - run: scripts/build xz:host
      - run: scripts/build sed:host
      - run: scripts/build gettext:host
      - run: scripts/build pkg-config:host
      - run: scripts/build m4:host
      - run: scripts/build autoconf:host
      - run: scripts/build automake:host
      - run: scripts/build libtool:host
      - run: scripts/build intltool:host
      - run: scripts/build autoconf-archive:host
      - run: scripts/build bison:host
      - run: scripts/build flex:host
      - run: scripts/build linux:host
      - run: scripts/build binutils:host
      - save_cache:
          key: build-v1
          paths:
            - sources
            - build.Lakka-Generic.x86_64-2.1-devel/
      - restore_cache:
          keys:
            - buildcache
      - run: make image -j1
      - save_cache:
          key: buildcache
          paths:
            - build.Lakka-Generic.x86_64-2.1-devel

